# Generated by Django 5.1.1 on 2024-09-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(default='test', max_length=165),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='preparation_time_unit',
            field=models.CharField(default=1, max_length=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings_unit',
            field=models.CharField(default=1, max_length=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(default=1, max_length=65),
            preserve_default=False,
        ),
    ]
